package ch.addere.keystrokecounter.core.domain.model

/**
 * Represents any type sign that changes a document. A symbol can be any regular character or number
 * such as 'a' or '2' as well as a whitespace or a tabulator. Even emojis are symbols.
 *
 * A symbol is independent of different encodings such as UTF-8 or UTF-16. Line breaks are treated
 * as symbols as well.
 */
data class Symbol(val value: Int)

val LINE_BREAK: Symbol = Symbol('\n'.code)
val TAB: Symbol = Symbol('\t'.code)
val BLANK: Symbol = Symbol(' '.code)

val A: Symbol = Symbol('a'.code)
val B: Symbol = Symbol('b'.code)
val C: Symbol = Symbol('c'.code)
val D: Symbol = Symbol('d'.code)
val E: Symbol = Symbol('e'.code)
val F: Symbol = Symbol('f'.code)
val G: Symbol = Symbol('g'.code)
val H: Symbol = Symbol('h'.code)
val I: Symbol = Symbol('i'.code)
val J: Symbol = Symbol('j'.code)
val K: Symbol = Symbol('k'.code)
val L: Symbol = Symbol('l'.code)
val M: Symbol = Symbol('m'.code)
val N: Symbol = Symbol('n'.code)
val O: Symbol = Symbol('o'.code)
val P: Symbol = Symbol('p'.code)
val Q: Symbol = Symbol('q'.code)
val R: Symbol = Symbol('r'.code)
val S: Symbol = Symbol('s'.code)
val T: Symbol = Symbol('t'.code)
val U: Symbol = Symbol('u'.code)
val V: Symbol = Symbol('v'.code)
val W: Symbol = Symbol('w'.code)
val X: Symbol = Symbol('x'.code)
val Y: Symbol = Symbol('y'.code)
val Z: Symbol = Symbol('z'.code)

val A_CAPITAL: Symbol = Symbol('A'.code)
val B_CAPITAL: Symbol = Symbol('B'.code)
val C_CAPITAL: Symbol = Symbol('C'.code)
val D_CAPITAL: Symbol = Symbol('D'.code)
val E_CAPITAL: Symbol = Symbol('E'.code)
val F_CAPITAL: Symbol = Symbol('F'.code)
val G_CAPITAL: Symbol = Symbol('G'.code)
val H_CAPITAL: Symbol = Symbol('H'.code)
val I_CAPITAL: Symbol = Symbol('I'.code)
val J_CAPITAL: Symbol = Symbol('J'.code)
val K_CAPITAL: Symbol = Symbol('K'.code)
val L_CAPITAL: Symbol = Symbol('L'.code)
val M_CAPITAL: Symbol = Symbol('M'.code)
val N_CAPITAL: Symbol = Symbol('N'.code)
val O_CAPITAL: Symbol = Symbol('O'.code)
val P_CAPITAL: Symbol = Symbol('P'.code)
val Q_CAPITAL: Symbol = Symbol('Q'.code)
val R_CAPITAL: Symbol = Symbol('R'.code)
val S_CAPITAL: Symbol = Symbol('S'.code)
val T_CAPITAL: Symbol = Symbol('T'.code)
val U_CAPITAL: Symbol = Symbol('U'.code)
val V_CAPITAL: Symbol = Symbol('V'.code)
val W_CAPITAL: Symbol = Symbol('W'.code)
val X_CAPITAL: Symbol = Symbol('X'.code)
val Y_CAPITAL: Symbol = Symbol('Y'.code)
val Z_CAPITAL: Symbol = Symbol('Z'.code)
